const supabase = require('../config/supabase');

/**
 * Insert a generated website into the database
 * Note: ID is auto-generated by Supabase (UUID with gen_random_uuid())
 * @param {Object} websiteData - Website data without ID
 * @returns {Promise<Object>} Inserted website record with generated ID
 */
const insertGeneratedSite = async (websiteData) => {
    try {
        const { data, error } = await supabase
            .from('generated_sites')
            .insert([{
                business_name: websiteData.businessName,
                business_type: websiteData.businessType,
                description: websiteData.description,
                html: websiteData.html,
                css: websiteData.css,
                js: websiteData.js,
                content_json: websiteData.contentJSON,
                template_name: websiteData.templateName,
            }])
            .select()
            .single();

        if (error) {
            console.error('Database insert error:', error);
            throw new Error(`Failed to insert website: ${error.message}`);
        }

        return data;
    } catch (error) {
        console.error('Error in insertGeneratedSite:', error);
        throw error;
    }
};

/**
 * Fetch a generated website by ID from the database
 * @param {string} id - Website UUID
 * @returns {Promise<Object|null>} Website record or null if not found
 */
const fetchGeneratedSite = async (id) => {
    try {
        const { data, error } = await supabase
            .from('generated_sites')
            .select('*')
            .eq('id', id)
            .single();

        if (error) {
            if (error.code === 'PGRST116') {
                // No rows returned
                return null;
            }
            console.error('Database fetch error:', error);
            throw new Error(`Failed to fetch website: ${error.message}`);
        }

        return data;
    } catch (error) {
        console.error('Error in fetchGeneratedSite:', error);
        throw error;
    }
};

module.exports = {
    insertGeneratedSite,
    fetchGeneratedSite,
};
